### ISSUE TITLE
Unexpected Token W Error

### ISSUE THREAD

**Issue by baubaid** [autocomplete-python/autocomplete-python#244] opened 2016-10-29 17:01 UTC
Hi, I would love to use this package but every time I enable it and I write a single letter in my Python script, I get this error.

I've also noticed that autocomplete-plus works on its own when I disable autocomplete-python, but as soon as I enable autocomplete-python, this error shows up and no suggestions show up at all. When I disable autocomplete-plus but keep autocomplete-python, the error goes away but no suggestions show up.

It also shows up consistently.

EDIT/UPDATE: I did some tinkering around and the package works fine when I'm writing a new python script. It seems that the error is coming from the "from gurobipy import *" line I have at the beginning of my script, and it seems that removing that line fixes the issue.

However, I also tried changing it to "import gurobipy as gb" and then the error disappeared, but as soon as I finished changing my script to incorporate that change, I got the error again. I found that a bit weird.

Any help will be appreciated!

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12.1
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v1.8.7
### Stack Trace

Uncaught SyntaxError: Unexpected token W

```
SyntaxError: Unexpected token W
    at Object.parse (native)
    at module.exports._deserialize (/Users/baubaid/.atom/packages/autocomplete-python/lib/provider.coffee:328:23)
    at provider.BufferedProcess.stdout (/Users/baubaid/.atom/packages/autocomplete-python/lib/provider.coffee:51:10)
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:87:13)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:531:20)
```
### Commands

```
     -2:02.2.0 core:move-up (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:01.8.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:01.6.0 core:move-up (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:01.4.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:01.2.0 core:move-up (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:01.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:00.8.0 core:move-up (atom-text-editor.editor.is-focused.autocomplete-active)
  5x -1:59.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:57.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:57.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:57.1.0 core:save (atom-text-editor.editor.is-focused)
     -1:51.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:33.2.0 core:copy (atom-text-editor.editor.mini.is-focused)
  2x -0:31.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:24.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -0:01.0 core:backspace (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "auto-detect-indentation",
      "autoclose",
      "emmet",
      "latextools"
    ],
    "packagesWithKeymapsDisabled": [
      "python-tools"
    ],
    "telemetryConsent": "no"
  },
  "autocomplete-python": {
    "fuzzyMatcher": false,
    "outputProviderErrors": true,
    "pythonPaths": "/Users/baubaid/anaconda/bin/python",
    "useSnippets": "all"
  }
}
```
### Installed Packages

``` coffee
# User
ask-stack, v2.2.0 (inactive)
atom-beautify, v0.29.13 (active)
auto-detect-indentation, v1.3.0 (inactive)
autoclose, v0.0.2 (inactive)
autocomplete-bibtex, v0.6.2 (active)
autocomplete-python, v1.8.7 (active)
build, v0.66.0 (active)
busy, v0.7.0 (active)
color-picker, v2.2.2 (active)
dash, v1.7.0 (inactive)
emmet, v2.4.3 (inactive)
file-icons, v1.7.23 (active)
git-plus, v5.18.0 (active)
highlight-selected, v0.11.2 (active)
Hydrogen, v0.14.0 (inactive)
ink, v0.5.3 (active)
julia-client, v0.5.9 (active)
language-julia, v0.10.0 (active)
language-latex, v1.0.0 (active)
latex, v0.38.1 (active)
latex-autocomplete, v1.0.0 (active)
latexer, v0.3.0 (active)
latextools, v0.8.5 (inactive)
linter, v1.11.18 (active)
linter-csslint, v1.3.3 (active)
linter-htmlhint, v1.3.1 (active)
linter-pep8, v1.3.2 (active)
minimap, v4.25.6 (active)
minimap-highlight-selected, v4.4.0 (active)
open-in-browser, v0.4.7 (inactive)
pdf-view, v0.50.0 (active)
pigments, v0.37.0 (active)
python-tools, v0.6.8 (active)
save-session, v0.15.7 (active)
script, v3.11.1 (inactive)
set-syntax, v0.3.2 (active)
term3, v0.22.1 (active)
todo-show, v1.7.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (inactive)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment] 2016-10-31 11:03
The exception happened because we failed to parse JSON response from python script with Jedi. We only know that it's begins with `W` unfortunately. I have made a fix to output more details in such cases. This is not going to resolve your issue, but it will help me to understand it.

Could you please:
  * Update to v1.8.8 to include my fix
  * Turn on debug logs in package settings
    ![image](https://cloud.githubusercontent.com/assets/193864/19852051/01e4e45c-9f9c-11e6-9480-dd22147c82b3.png)
  * Open `dev tools` (`cmd + opt + I`) -> console tab
  * Show me everything you can (it may include parts of your code, remove everything you don't want to show). Mostly I'm interested in `Deserializing response from Jedi` parts.

The exception by itself should provide more information as well.

**Comment by baubaid** [comment] 2016-10-31 14:20
Thanks for your response! I got this as an output. Let me know if this is enough or not. I'm also not sure if there is a better way to display the output. I've marked with "***" the beginning of the part I think you're looking for. I got this error after beginning to type in the keyword "def".

It seems that this has to do with the GurobiPy I'm using to do some optimization. Let me know if you need any help on that.

VM2300:1 Uncaught SyntaxError: Unexpected token W
module.exports._deserialize @ provider.coffee:328
provider.BufferedProcess.stdout @ provider.coffee:51
(anonymous function) @ buffered-process.coffee:119
emitOne @ events.js:90
emit @ events.js:182
readableAddChunk @ _stream_readable.js:153
Readable.push @ _stream_readable.js:111
onread @ net.js:531
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:8630 POST https://is.gd/create.php?format=simple 400 ()send @ /Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:8630jQuery.extend.ajax @ /Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:8166
(anonymous function) @ notification-issue.coffee:43
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3256 

Uncaught (in promise)
Object {readyState: 4, responseText: "Error: Please enter a valid URL to shorten", status: 400, statusText: "error"}abort: ( statusText )always: ()complete: ()done: ()error: ()fail: ()getAllResponseHeaders: ()getResponseHeader: ( key )overrideMimeType: ( type )pipe: ( /* fnDone, fnFail, fnProgress */ )progress: ()promise: ( obj )readyState: 4responseText: "Error: Please enter a valid URL to shorten"setRequestHeader: ( name, value )state: ()status: 400statusCode: ( map )statusText: "error"success: ()then: ( /* fnDone, fnFail, fnProgress */ )__proto__: Object(anonymous function) @ /Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3256fire @ /Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3099self.fireWith @ /Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:3211done @ /Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:8266(anonymous function) @ /Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:8605
log.coffee:5 autocomplete-python: Serializing request to be sent to Jedi Object {id: "9afa6d04bf6135ef849b350a28f760d1", prefix: "def", lookup: "completions", path: "/Users/path_to_file", source: """"↵Solves a multi-commodity flow problem on a tim…st, locationnames, locationindices, traveltimes)↵"…}
log.coffee:5 autocomplete-python: Pending requests: 1 Object {}

*** I'm guessing this is the part you were looking for ***
log.coffee:5 autocomplete-python: Deserealizing response from Jedi Warning: Failed to open log file 'gurobi.log'
{"id": "9afa6d04bf6135ef849b350a28f760d1", "results": [{"text": "def", "rightLabel": "", "type": "keyword", "description": ""}, {"text": "del", "rightLabel": "", "type": "keyword", "description": ""}, {"text": "delattr", "rightLabel": "", "type": "builtin", "description": "delattr(object, name)\n\nDelete a named attribute on an object; delattr(x, 'y') is equivalent to\n``del x.y''."}, {"text": "DeprecationWarning", "rightLabel": "", "type": "builtin", "description": "Base class for warnings about deprecated features."}, {"text": "dict", "rightLabel": "", "type": "builtin", "description": "dict() -> new empty dictionary\ndict(mapping) -> new dictionary initialized from a mapping object's\n    (key, value) pairs\ndict(iterable) -> new dictionary initialized as if via:\n    d = {}\n    for k, v in iterable:\n        d[k] = v\ndict(**kwargs) -> new dictionary initialized with the name=value pairs\n    in the keyword argument list.  For example:  dict(one=1, two=2)"}, {"text": "dir", "rightLabel": "", "type": "builtin", "description": "dir([object]) -> list of strings\n\nIf called without an argument, return the names in the current scope.\nElse, return an alphabetized list of names comprising (some of) the attributes\nof the given object, and of attributes reachable from it.\nIf the object supplies a method named __dir__, it will be used; otherwise\nthe default dir() logic is used and returns:\n  for a module object: the module's attributes.\n  for a class object:  its attributes, and recursively the attributes\n    of its bases.\n  for any other object: its attributes, its class's attributes, and\n    recursively the attributes of its class's base classes."}, {"text": "divmod", "rightLabel": "", "type": "builtin", "description": "divmod(x, y) -> (quotient, remainder)\n\nReturn the tuple (x//y, x%y).  Invariant: div*y + mod == x."}]}
{"id": "9afa6d04bf6135ef849b350a28f760d1", "results": [{"text": "def", "rightLabel": "", "type": "keyword", "description": ""}, {"text": "del", "rightLabel": "", "type": "keyword", "description": ""}, {"text": "delattr", "rightLabel": "", "type": "builtin", "description": "delattr(object, name)\n\nDelete a named attribute on an object; delattr(x, 'y') is equivalent to\n``del x.y''."}, {"text": "DeprecationWarning", "rightLabel": "", "type": "builtin", "description": "Base class for warnings about deprecated features."}, {"text": "dict", "rightLabel": "", "type": "builtin", "description": "dict() -> new empty dictionary\ndict(mapping) -> new dictionary initialized from a mapping object's\n    (key, value) pairs\ndict(iterable) -> new dictionary initialized as if via:\n    d = {}\n    for k, v in iterable:\n        d[k] = v\ndict(**kwargs) -> new dictionary initialized with the name=value pairs\n    in the keyword argument list.  For example:  dict(one=1, two=2)"}, {"text": "dir", "rightLabel": "", "type": "builtin", "description": "dir([object]) -> list of strings\n\nIf called without an argument, return the names in the current scope.\nElse, return an alphabetized list of names comprising (some of) the attributes\nof the given object, and of attributes reachable from it.\nIf the object supplies a method named __dir__, it will be used; otherwise\nthe default dir() logic is used and returns:\n  for a module object: the module's attributes.\n  for a class object:  its attributes, and recursively the attributes\n    of its bases.\n  for any other object: its attributes, its class's attributes, and\n    recursively the attributes of its class's base classes."}, {"text": "divmod", "rightLabel": "", "type": "builtin", "description": "divmod(x, y) -> (quotient, remainder)\n\nReturn the tuple (x//y, x%y).  Invariant: div*y + mod == x."}]}
{"id": "9afa6d04bf6135ef849b350a28f760d1", "results": [{"text": "def", "rightLabel": "", "type": "keyword", "description": ""}, {"text": "del", "rightLabel": "", "type": "keyword", "description": ""}, {"text": "delattr", "rightLabel": "", "type": "builtin", "description": "delattr(object, name)\n\nDelete a named attribute on an object; delattr(x, 'y') is equivalent to\n``del x.y''."}, {"text": "DeprecationWarning", "rightLabel": "", "type": "builtin", "description": "Base class for warnings about deprecated features."}, {"text": "dict", "rightLabel": "", "type": "builtin", "description": "dict() -> new empty dictionary\ndict(mapping) -> new dictionary initialized from a mapping object's\n    (key, value) pairs\ndict(iterable) -> new dictionary initialized as if via:\n    d = {}\n    for k, v in iterable:\n        d[k] = v\ndict(**kwargs) -> new dictionary initialized with the name=value pairs\n    in the keyword argument list.  For example:  dict(one=1, two=2)"}, {"text": "dir", "rightLabel": "", "type": "builtin", "description": "dir([object]) -> list of strings\n\nIf called without an argument, return the names in the current scope.\nElse, return an alphabetized list of names comprising (some of) the attributes\nof the given object, and of attributes reachable from it.\nIf the object supplies a method named __dir__, it will be used; otherwise\nthe default dir() logic is used and returns:\n  for a module object: the module's attributes.\n  for a class object:  its attributes, and recursively the attributes\n    of its bases.\n  for any other object: its attributes, its class's attributes, and\n    recursively the attributes of its class's base classes."}, {"text": "divmod", "rightLabel": "", "type": "builtin", "description": "divmod(x, y) -> (quotient, remainder)\n\nReturn the tuple (x//y, x%y).  Invariant: div*y + mod == x."}]}

log.coffee:5 autocomplete-python: Got 4 lines

**Comment by sadovnychyi** [comment] 2016-11-01 11:01
I got a fix for #161 which is very similar to this issue. I didn't find a source code for library you use (`gurobi`) but I believe they use `.so` files as well as `kivy.`

See https://github.com/davidhalter/jedi/issues/793.

Please re-open if it's not actually fixed in 1.8.9.

**Comment by baubaid** [comment] 2016-11-01 13:03
Thanks. I've updated the package and restarted Atom and now I get the following error. Should I open a new issue?

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12.1
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v1.8.9


### Stack Trace

Uncaught Error: Failed to parse JSON from "Warning: Failed to open log file 'gurobi.log'".
Original exception: SyntaxError: Unexpected token W

```
At /Users/baubaid/.atom/packages/autocomplete-python/lib/provider.coffee:331

Error: Failed to parse JSON from "Warning: Failed to open log file 'gurobi.log'".
Original exception: SyntaxError: Unexpected token W
    at module.exports._deserialize (/Users/baubaid/.atom/packages/autocomplete-python/lib/provider.coffee:331:19)
    at provider.BufferedProcess.stdout (/Users/baubaid/.atom/packages/autocomplete-python/lib/provider.coffee:51:10)
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:87:13)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:531:20)
```

### Commands

```
     -0:55.3.0 core:copy (atom-text-editor.editor.is-focused)
  3x -0:54.4.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:53 editor:newline (atom-text-editor.editor.is-focused)
     -0:25.4.0 core:copy (atom-text-editor.editor.is-focused)
  2x -0:24.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:24 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "auto-detect-indentation",
      "autoclose",
      "emmet",
      "latextools",
      "open-in-browser",
      "linter-csslint",
      "linter-htmlhint"
    ],
    "packagesWithKeymapsDisabled": [
      "python-tools"
    ],
    "telemetryConsent": "no"
  },
  "autocomplete-python": {
    "extraPaths": "/Users/baubaid/anaconda/lib/python2.7/site-packages",
    "outputDebug": true,
    "outputProviderErrors": true,
    "pythonPaths": "/Users/baubaid/anaconda/bin/python",
    "useSnippets": "all"
  }
}
```

### Installed Packages

```coffee
# User
ask-stack, v2.2.0 (inactive)
atom-beautify, v0.29.13 (inactive)
auto-detect-indentation, v1.3.0 (inactive)
autoclose, v0.0.2 (inactive)
autocomplete-bibtex, v0.6.2 (active)
autocomplete-python, v1.8.9 (active)
build, v0.66.0 (active)
busy, v0.7.0 (active)
color-picker, v2.2.2 (active)
dash, v1.7.0 (inactive)
emmet, v2.4.3 (inactive)
file-icons, v1.7.23 (active)
git-plus, v5.21.0 (active)
highlight-selected, v0.11.2 (active)
Hydrogen, v0.15.0 (inactive)
ink, v0.5.3 (active)
julia-client, v0.5.9 (active)
language-julia, v0.10.0 (active)
language-latex, v1.0.0 (active)
latex, v0.39.0 (inactive)
latex-autocomplete, v1.0.0 (active)
latexer, v0.3.0 (active)
latextools, v0.8.5 (inactive)
linter, v1.11.18 (active)
linter-csslint, v1.3.3 (inactive)
linter-htmlhint, v1.3.1 (inactive)
linter-pep8, v1.3.2 (active)
minimap, v4.25.6 (active)
minimap-highlight-selected, v4.4.0 (active)
open-in-browser, v0.4.7 (inactive)
pdf-view, v0.50.0 (active)
pigments, v0.37.0 (active)
python-tools, v0.6.8 (active)
save-session, v0.15.7 (active)
script, v3.11.1 (inactive)
set-syntax, v0.3.2 (active)
term3, v0.22.1 (active)
todo-show, v1.7.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (inactive)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment] 2016-11-01 13:07
No need for new issue, it's same error. How can I get that gurobi library so I can reproduce this?

**Comment by baubaid** [comment] 2016-11-01 13:10
I think you can get the Python library via a `pip install gurobipy`. The issue is getting the Gurobi Optimization Solver itself as it is commercial software (however, it is free with an academic license if you have a .edu email).

**Comment by sadovnychyi** [comment] 2016-11-02 09:22
Does not work for me:
```
Collecting gurobipy
  Could not find a version that satisfies the requirement gurobipy (from versions: )
No matching distribution found for gurobipy
```

The problem here is that Jedi actually executes .so modules and if they output something in stdout (logs in this case) – you will see this error, since this plugin expects only JSON formatted communication. Ideally this should be fixed within Jedi – it should suppress all such things.

I did fix same issue for `kivy`  (I was able to reproduce it, and after this fix it's gone). But I cannot reproduce this one without the code.

You could try to suppress stdout/stderr by yourself [here](https://github.com/autocomplete-python/autocomplete-python/blob/master/lib/completion.py#L371). Maybe I'm missing something.

**Comment by baubaid** [comment] 2016-11-02 12:56
Well, here are two ways to install the package:
https://www.gurobi.com/documentation/6.5/quickstart_mac/the_gurobi_python_interfac.html
and
https://www.gurobi.com/documentation/6.5/quickstart_mac/the_gurobi_python_interfac.html

I guess the first one needs a Gurobi license but the second one doesn't, but I'm not sure how much of use the package would be without the solver.

And I'm not exactly a proficient coder, so I wouldn't exactly know what to do there, but what you're saying makes sense to me. Does it also just stop there and not show any autocomplete suggestions because of that?

**Comment by sadovnychyi** [comment] 2017-02-11 17:34
Closing this as I cannot reproduce what's left of this issue. Please create new one if it's still shows up.

**Closed by sadovnychyi** 2017-02-11 17:34 UTC
Labels: bug, help wanted
